Fix machine object reference error in problem_builder
- Store machine objects returned by add_machine() in self.machine_objects
- Use stored machine objects when adding modes instead of trying to access
  model.machines (which doesn't exist in PyJobShop)
- Update solution_parser to use problem_builder.machine_objects

Error was: AttributeError: 'Model' object has no attribute 'machines'
Fix: Store machine objects in a list when creating them (line 49-53)